### ISSUE TITLE
我测试了一下,你的hevc加速不生效

### ISSUE THREAD

**Issue by 277383761** [koor/Deskmini-110-Hackintosh-Ventura#1]
![image](https://github.com/koor/Deskmini-110-Hackintosh-Ventura/assets/49450669/d3fe1107-1496-4bda-8382-578886b4063e)
这是我自己的旧代10.6.5时的是ok的,但你的配置仿佛不行,测试工具名叫videoproc

**Comment by koor** [comment]
确实是的，我测试同样不支持hevc。你有合适的efi吗？

**Comment by 277383761** [comment]
> 确实是的，我测试同样不支持hevc。你有合适的efi吗？

我没装过13系统,不清楚了,我现在还用10.15.7,但不想八代核显还会引起定格死机的问题,唉.这机器也没啥意思了.

**Comment by koor** [comment]
> > 确实是的，我测试同样不支持hevc。你有合适的efi吗？
> 
> 我没装过13系统,不清楚了,我现在还用10.15.7,但不想八代核显还会引起定格死机的问题,唉.这机器也没啥意思了.

已修复，删除`AAPL,slot-name`这个key就可以实现hevc硬解了

**Comment by 277383761** [comment]
> > > 确实是的，我测试同样不支持hevc。你有合适的efi吗？
> > 
> > 
> > 我没装过13系统,不清楚了,我现在还用10.15.7,但不想八代核显还会引起定格死机的问题,唉.这机器也没啥意思了.
> 
> 已修复，删除`AAPL,slot-name`这个key就可以实现hevc硬解了

这台机器偶尔会定格死机的问题,听说是电流的问题.有一个帖子可以解决,但是我刷入了其中的bios后,调了几下,反而进黑苹果进度条时就死机了.更加内个了.注意备份原bios文件.或者你有什么好的见解分享一下.
https://www.jianshu.com/p/ee42904ebb53

https://www.chinafix.com/thread-1353197-1-1.html

以上两个帖子第一个帖子说可以解决定格死机的问题,第二个帖子内含有此开放OC调式的bios文件.我刷入过,可以用于八代i3 8100或i7 8850h的,注意要刷未启用ME的版本.也注意备份原来的bios

**Comment by koor** [comment]
> > > > 确实是的，我测试同样不支持hevc。你有合适的efi吗？
> > > 
> > > 
> > > 我没装过13系统,不清楚了,我现在还用10.15.7,但不想八代核显还会引起定格死机的问题,唉.这机器也没啥意思了.
> > 
> > 
> > 已修复，删除`AAPL,slot-name`这个key就可以实现hevc硬解了
> 
> 这台机器偶尔会定格死机的问题,听说是电流的问题.有一个帖子可以解决,但是我刷入了其中的bios后,调了几下,反而进黑苹果进度条时就死机了.更加内个了.注意备份原bios文件.或者你有什么好的见解分享一下. https://www.jianshu.com/p/ee42904ebb53
> 
> https://www.chinafix.com/thread-1353197-1-1.html
> 
> 以上两个帖子第一个帖子说可以解决定格死机的问题,第二个帖子内含有此开放OC调式的bios文件.我刷入过,可以用于八代i3 8100或i7 8850h的,注意要刷未启用ME的版本.也注意备份原来的bios

我从没遇到过定格死机的问题，不清楚是否和u有关。我用的bios是 https://github.com/damnnfo/DeskMini-110-COM

有个妹子dfc643对此机器折腾颇深，你可以看下这个帖子是不是你遇到的问题 https://v2ex.com/t/718067
但这个妹妹好像删号隐退江湖了，里面提到的修改程序[dk110-igpu-fixer](https://github.com/dfc643/dk110-igpu-fixer)链接已经失效

**Comment by 277383761** [comment]
你的居然没有定格死机过?? 你是不是长年用着1080p的显示器? 而我用的是4K显示器? 我已经遇到许多相同机型出现定格死机的情况了,你运气不错

**Comment by koor** [comment]
> 你的居然没有定格死机过?? 你是不是长年用着1080p的显示器? 而我用的是4K显示器? 我已经遇到许多相同机型出现定格死机的情况了,你运气不错

曾经有连接过4k显示器，但在gpu占用高时屏幕会突然黑屏1s左右，随后恢复，在windows下也一样，我以为是8100的uhd630带不动的缘故，没怀疑到黑苹果头上，索性继续连1080p显示器了

**Comment by 277383761** [comment]
这就对上了,这机器带4k显示器,PD接口带宽是足够的,但要么黑屏一下,要么闪烁一下,现在嘛都会定格死机一下.唉,挺折腾的,我现在都是用了一个usb上面带的grub把显卡电流调到最低,然后再把分辨率从4k降到3k才稍微稳定一些,但一天下来偶尔还会来一次死机.那个妹纸的bios我跟着调了,不但没解决死机,反而死机概率增加了.可能是我不懂调,也有可能是我的cpu同她不一样

**Comment by koor** [comment]
> 这就对上了,这机器带4k显示器,PD接口带宽是足够的,但要么黑屏一下,要么闪烁一下,现在嘛都会定格死机一下.唉,挺折腾的,我现在都是用了一个usb上面带的grub把显卡电流调到最低,然后再把分辨率从4k降到3k才稍微稳定一些,但一天下来偶尔还会来一次死机.那个妹纸的bios我跟着调了,不但没解决死机,反而死机概率增加了.可能是我不懂调,也有可能是我的cpu同她不一样

原来如此。看来是通病，那应该是无解了，现在这机器也没啥折腾价值了
